runtime devel deps
building hello world requires:

glibc-headers:
/usr/lib64/ghc-8.10.7/include/stg/Types.h:44:10: error:
     fatal error: inttypes.h: No such file or directory

gmp-devel:
/usr/bin/ld: cannot find -lgmp: No such file or directory
collect2: error: ld returned 1 exit status

libffi-devel and numactl-devel:
/usr/bin/ld: cannot find -lffi: No such file or directory
/usr/bin/ld: cannot find -lnuma: No such file or directory
collect2: error: ld returned 1 exit status